apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: petclinic2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
     securityContext:
       fsGroup: 1
     containers:
     - name: petclinic2
       image: {{ REGISTRY }}/petclinictest:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
         protocol: TCP
