apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: cicdpipeline/ansible:2.0
        ports:
        - containerPort: 443
          protocol: TCP

